name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use the Node version that suits your project

    - name: Install dependencies
      run: npm install
      working-directory: ./my-node-project

    # - name: Build
    #   run: npm run build
    #   working-directory: ./my-node-project

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: public    # The folder the action should deploy.
        working-directory: ./my-node-project # Set this if your public folder is inside my-node-project
